services:
  todo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    container_name: todo
    restart: always
    environment:
      - MONGODB_URI=$MONGODB_URI