name: Monitoring Pipeline
on:
  push:
    paths:
    - monitoring/**
    branches:
      - feat/init-cicd
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    env: 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy project to runner server
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          BACKUP_DIR="/home/ubuntu/app/backups/monitoring/$TIMESTAMP"
          APP_DIR="/home/ubuntu/app/monitoring"
          mkdir -p $BACKUP_DIR
          mkdir -p $APP_DIR
          cp -r $APP_DIR* $BACKUP_DIR/
          rsync -av --delete . $APP_DIR


      - name: Docker Compose Up

        run: |
          APP_DIR="/home/ubuntu/app/todo"        
          cd $APP_DIR        
          GRAFANA_PASSWORD=${{ secrets.GRAFANA_PASSWORD }}
          docker compose down || true          
          GRAFANA_PASSWORD=$GRAFANA_PASSWORD docker compose up -d

      - name: Clean up old backups
        run: |
          find /home/ubuntu/app/backups/monitoring/ -type d -mtime +30 -exec rm -rf {} \;